const fs = require('fs');
require('dotenv').config();

const targetPath = './src/environments/environment.firebase.ts';

const envConfigFile = `// This file is auto-generated by set-env.js
export const environmentFirebase = {
  firebase: {
    apiKey: '${process.env.FIREBASE_API_KEY}',
    authDomain: '${process.env.FIREBASE_AUTH_DOMAIN}',
    projectId: '${process.env.FIREBASE_PROJECT_ID}',
    storageBucket: '${process.env.FIREBASE_STORAGE_BUCKET}',
    messagingSenderId: '${process.env.FIREBASE_MESSAGING_SENDER_ID}',
    appId: '${process.env.FIREBASE_APP_ID}',
    measurementId: '${process.env.FIREBASE_MEASUREMENT_ID}'
  }
};
`;

fs.writeFileSync(targetPath, envConfigFile);
console.log('Firebase environment file generated correctly at ' + targetPath);
