const fs = require('fs');
require('dotenv').config();

const dir = './src/environments';
if (!fs.existsSync(dir)) {
  fs.mkdirSync(dir, { recursive: true });
}

// 1. Firebase Environment
const firebasePath = `${dir}/environment.firebase.ts`;
const firebaseConfig = `// This file is auto-generated by set-env.js
export const environmentFirebase = {
  firebase: {
    apiKey: '${process.env.FIREBASE_API_KEY || ''}',
    authDomain: '${process.env.FIREBASE_AUTH_DOMAIN || ''}',
    projectId: '${process.env.FIREBASE_PROJECT_ID || ''}',
    storageBucket: '${process.env.FIREBASE_STORAGE_BUCKET || ''}',
    messagingSenderId: '${process.env.FIREBASE_MESSAGING_SENDER_ID || ''}',
    appId: '${process.env.FIREBASE_APP_ID || ''}',
    measurementId: '${process.env.FIREBASE_MEASUREMENT_ID || ''}'
  }
};
`;

// 2. Standard Environment (Dev)
const envPath = `${dir}/environment.ts`;
const envConfig = `// This file is auto-generated by set-env.js
export const environment = {
  production: false,
  apiAuthUrl: '${process.env.API_AUTH_URL || ''}',
  apiTemplateUrl: '${process.env.API_TEMPLATE_URL || ''}'
};
`;

// 3. Production Environment
const prodPath = `${dir}/environment.prod.ts`;
const prodConfig = `// This file is auto-generated by set-env.js
export const environment = {
  production: true,
  apiAuthUrl: '${process.env.API_AUTH_URL || ''}',
  apiTemplateUrl: '${process.env.API_TEMPLATE_URL || ''}'
};
`;

fs.writeFileSync(firebasePath, firebaseConfig);
fs.writeFileSync(envPath, envConfig);
fs.writeFileSync(prodPath, prodConfig);

console.log('Environment files generated successfully in ' + dir);
