// This file is auto-generated by set-env.js
export const environmentFirebase = {
  firebase: {
    apiKey: 'AIzaSyB81GU1t2J51Om1xoOsdrGU7PeifIB0-uk',
    authDomain: 'confex-7540a.firebaseapp.com',
    projectId: 'confex-7540a',
    storageBucket: 'confex-7540a.firebasestorage.app',
    messagingSenderId: '1096625652336',
    appId: '1:1096625652336:web:136681e18735e2ad012ab5',
    measurementId: 'G-PLE6F1X52J'
  }
};
